### Import Statements Used:

In [1]:
import numpy as np

##**Practice:**

# **Q1**

In [2]:
# References: Used Numpy notebook from class
'''
1(a) Form this array without typing out all of the numbers.
'''
Z = np.arange(256)

'''
1(b) Reshape this array to be a 16x16 matrix
'''
Z_reshaped = Z.reshape((16, 16))
#print(Z_reshaped) # Sanity check

'''
1(c) Determine Z1, Z2, Z3, and Z4, which are the 8 × 8 matrices that our matrix can be split into.
'''
Z1 = Z_reshaped[:8, :8]  # upper left
Z2 = Z_reshaped[:8, 8:]  # upper right
Z3 = Z_reshaped[8:, :8]  # lower left
Z4 = Z_reshaped[8:, 8:]  # lower right
#print(Z1,'\n', Z2,'\n', Z3,'\n', Z4, '\n')

'''
1(d) For each of Z1, Z2, Z3, and Z4, determine the sum of the 64 elements of the matrix.
'''
Z1_sum = np.sum(Z1)
print("Sum of Z1: ", Z1_sum)
Z2_sum = np.sum(Z2)
print("Sum of Z2: ", Z2_sum)
Z3_sum = np.sum(Z3)
print("Sum of Z3: ", Z3_sum)
Z4_sum = np.sum(Z4)
print("Sum of Z4: ", Z4_sum)



Sum of Z1:  3808
Sum of Z2:  4320
Sum of Z3:  12000
Sum of Z4:  12512


# **Q2**

In [3]:
'''
A magic square is a matrix all of whose row sums, column sums and the sums of the two diagonals are
the same. (One diagonal of a matrix goes from the top left to the bottom right, the other diagonal
goes from top right to bottom left.) Show by direct computation that the matrix A given by the line
below is a magic square.
'''

'\nA magic square is a matrix all of whose row sums, column sums and the sums of the two diagonals are\nthe same. (One diagonal of a matrix goes from the top left to the bottom right, the other diagonal\ngoes from top right to bottom left.) Show by direct computation that the matrix A given by the line\nbelow is a magic square.\n'

In [4]:
'''
References:
For diagonal sum: https://numpy.org/doc/stable/reference/generated/numpy.diagonal.html
'''

#  Matrix A (from problem)
A = np.array([
    [17, 24, 1, 8, 15],
    [23, 5, 7, 14, 16],
    [4, 6, 13, 20, 22],
    [10, 12, 19, 21, 3],
    [11, 18, 25, 2, 9]
    ])

# For row and col sum computations:
row_sum = np.sum(A, axis=1)   # axis 1 indicates sum over rows
col_sum = np.sum(A, axis=0)   # axis 0 indicates sum over cols

# Row min and max
row_min = np.min(row_sum)
row_max = np.max(row_sum)

# Col min and max
col_min = np.min(col_sum)
col_max = np.max(col_sum)

# For diagonal sums:
diag_sum = (np.trace(A)) # Trace function to compute sum
flipped_diag_sum = np.trace(np.fliplr(A))  # Flip to get other direction

if(row_min == row_max == col_min == col_max == diag_sum == flipped_diag_sum): # Check the 6 values
  print('A is a magic number! :)')
else:
  print('A is not a magic number :(')


A is a magic number! :)


## **Graded**

In [5]:
# Reference:
# Geeks 4 geeks for meshgrid examples:  https://www.geeksforgeeks.org/numpy-meshgrid-function/
# Broadcasting examples: https://numpy.org/doc/stable/user/basics.broadcasting.html

def solvefrob(coefs, b):
  '''
  This functions shows the solutions to the Forbes equation using broadcasting.

  Input:
    coefs: list() – coefficients a_i as a list
    b: int – right hand side, answer to equation.
  Output:
    sols: list() – A list of the possible coefficients that are solutions to the equation
  '''

  coef_size = len(coefs)

  x_range = [np.arange(b + 1)] * coef_size # Range for possible vlaues of coefficients
  all_sols = np.array(np.meshgrid(*x_range)).T.reshape(-1, coef_size) # Create a matrix  for all possible solutions

  coefs_array = np.array(coefs) # convert coefficients to a numpy array for broadcasting
  sols = all_sols[np.dot(all_sols, coefs_array) == b] # Broadcasting np.dot between possible solutions and coefficients

  return sols


valid = solvefrob([1, 2, 3, 5], 10) # Test the solution
print(valid)


[[ 0  5  0  0]
 [ 2  4  0  0]
 [ 4  3  0  0]
 [ 6  2  0  0]
 [ 8  1  0  0]
 [10  0  0  0]
 [ 1  3  1  0]
 [ 3  2  1  0]
 [ 5  1  1  0]
 [ 7  0  1  0]
 [ 0  2  2  0]
 [ 2  1  2  0]
 [ 4  0  2  0]
 [ 1  0  3  0]
 [ 1  2  0  1]
 [ 3  1  0  1]
 [ 5  0  0  1]
 [ 0  1  1  1]
 [ 2  0  1  1]
 [ 0  0  0  2]]
